### PR TITLE
Adding FPS support

### PR DESCRIPTION
**Pull request by kevalpatel2106**
Allowing developer to manage fps

### CODE REVIEW

**Comment by kevalpatel2106** [comment]
@JeroenMols any updates?

**Comment by JeroenMols** [comment]
@kevalpatel2106 terribly sorry it took me so long :)

Everything looks good, only thing that does bug me is the constructors for "CaptureConfiguration" are getting out of control. -> I'm going to deprecate them and replace it with a builder pattern. Once that's done I'll create a new Landscape video camera release.

**Comment by kevalpatel2106** [comment]
I was thinking for the same. There are too many parameters for camera config. We should replace it with the builder pattern.

**Comment by Dakor91** [comment]
Hi, do you have a rough estimation for the new release?

**Comment by JeroenMols** [comment]
@Dakor91 Sorry for the late reply (has been busy lately)
I've created a PR, hope to wrap this up next week :) https://github.com/JeroenMols/LandscapeVideoCamera/pull/49

**Pull request merged**
