### PR TITLE
Add target repository feature

### PR DESCRIPTION
**Pull request by C-driiic**
- Added an optional `extra` to the `VideoCaptureActivity` as `EXTRA_OUTPUT_DIRECTORY`
    - this extra (a string) is the name of your folder _(or sub-folder, see below)_
- Added this feature to the example `CaptureDemoFragment`
    - as an `EditText` where you enter the name of your folder (or sub-folder if you enter e.g. _folder/sub-folder_). When the `EditText` doesn't have focus anymore, it's automatically filled with the entire external directory path (in grey the default root path followed by your folder/sub-folder name in black). When the `EditText` gain focus again, the default root path is cleared out, leaving only what you have typed in - to avoid confusions.
- I have also updated the Readme file.
- I haven't touched the version number/code. _I have absolutely no clue if I should have done it or not._
- I have updated the buildToolsVersion from 26.x to 27.x and the gradle version from 3.x to 4.x - _but again, I did that to suits my needs but don't really know if I was suppose to do that or not, or if it affects you somehow._

### CODE REVIEW

**Comment by C-driiic** [comment]
Hum ...... Travis CI build failed!

Do I need to add: **- build-tools-27.0.0** to the .travis.yml file?

```yaml
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.0 # like this??
    - android-22
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
```

Cedric

**Comment by JeroenMols** [comment]
Can you try replacing:
    - build-tools-26.0.2

with:
    - build-tools-27.0.0

**Comment by C-driiic** [comment]
Hi,

And then? What's next?

BR
Cedric

**Comment by JeroenMols** [comment]
I'm not sure if this feature should be in this library. 

On one hand, it makes sense that certain apps would want to record private videos. But those should then be placed in the private storage of that app. (so not via this mechanism)
-> Frankly I don't even know that would be a good idea as video does consume a lot of disk space and this setup would not give the user granular control of what videos to delete or keep. (placing the burden of offering such a thing on the app integrating the library)

On the other hand the suggested mechanism isn't really easy to use: it's missing runtime permissions, granular error handling, based on file names iso uri's (what's suggested practice),...

What use cases did you have in mind?

**Comment by JeroenMols** [comment]
Closing this as no update on the use case

**Pull request closed without merging**
